name: Netlify Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: behide-internal

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Netlify CLI
        run: pnpm add -g netlify-cli

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Deploy
        run: netlify deploy --dir ./dist -s ${{ secrets.NETLIFY_SITE_ID }} --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} -m ${{ github.ref_name }}