name: Netlify Preview Deploy

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  deploy:
    name: Deploy
    runs-on: behide-internal

    steps:
      - uses: actions/checkout@v3


      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - args: [--frozen-lockfile]
            - args: [--global netlify-cli]

      - name: Build
        run: pnpm build

      - name: Deploy
        run: |
          netlify deploy
          --dir ./dist
          --site ${{ secrets.NETLIFY_SITE_ID }}
          --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
          --message ${{ github.event.pull_request.title }}
          --alias ${{ github.event.pull_request.title }}
